/**
 * Tailwind CSS Configuration
 * Converted to CommonJS for compatibility with Tailwind v4 and Next.js
 */
module.exports = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#dbe1ff",
        outline: "#737686",
        tertiary: "#535555",
        "secondary-fixed": "#d5e4f8",
        "on-secondary-fixed-variant": "#3a4858",
        "on-surface-variant": "#434655",
        "tertiary-fixed-dim": "#c6c6c7",
        "outline-variant": "#c3c6d7",
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary-fixed": "#0e1d2b",
        "surface-variant": "#e1e2e4",
        background: "#f8f9fb",
        "on-tertiary-fixed": "#1a1c1c",
        "secondary-container": "#d5e4f8",
        "surface-tint": "#0053db",
        error: "#ba1a1a",
        "inverse-on-surface": "#f0f1f3",
        "surface-dim": "#d9dadc",
        "surface-container-high": "#e7e8ea",
        "on-primary-container": "#eeefff",
        "on-error-container": "#93000a",
        "surface-bright": "#f8f9fb",
        "surface-container-low": "#f3f4f6",
        "on-secondary-container": "#576676",
        "inverse-primary": "#b4c5ff",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e1e2e4",
        "tertiary-container": "#6c6d6d",
        "primary-container": "#2563eb",
        "primary-fixed-dim": "#b4c5ff",
        surface: "#f8f9fb",
        "on-tertiary-fixed-variant": "#454747",
        primary: "#004ac6",
        secondary: "#516070",
        "secondary-fixed-dim": "#b9c8db",
        "inverse-surface": "#2e3132",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-background": "#191c1e",
        "on-secondary": "#ffffff",
        "on-surface": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#edeef0",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary-container": "#f0f0f0",
        "on-primary-fixed": "#00174b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sidebar_width: "280px",
        gutter: "24px",
        sm: "8px",
        base: "4px",
        xl: "32px",
        md: "16px",
        lg: "24px",
      },
      fontFamily: {
        "headline-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
