name: MERN CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cài đặt Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Kiểm tra Frontend
        run: |
          cd frontend
          npm install
          npm run build

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cài đặt Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Kiểm tra Backend
        run: |
          cd backend
          npm install
